services:
  express-app:
    build: .
    ports: 
      - "5000:5000"
    env_file: 
      - .env
    volumes: 
      - .:/app
      - /app/node_modules
    command: 
      npm run dev -- --legacy-watch
    
  mongo: 
    image: mongo:latest
    environment: 
        - MONGO_INITDB_ROOT_USERNAME=root
        - MONGO_INITDB_ROOT_PASSWORD=root
volumes: 
  mongo-data:


